source/includes/fact-online-archive-callout.rst
source/mongodump.txt
source/mongoexport.txt

Heads up for review: Online Archive docs are being published later today. In the meantime, the link to those docs will not work.
Staged:
[mongodump](https://docs-mongodbcom-staging.corp.mongodb.com/database-tools/jeffreyallen/DOCSP-10116/mongodump.html)
[mongoexport](https://docs-mongodbcom-staging.corp.mongodb.com/database-tools/jeffreyallen/DOCSP-10116/mongoexport.html)

(DOCSP-10116): Add callout to online archive on mongodump/export

---

config/redirects

Also removes the symlink line as symlinks don't do anything in Snooty-built repos.
@jeff-allen-mongo Could you review, please?

Update redirects base for subdomain consolidation

---

source/includes/fact-platform-support.rst

https://jira.mongodb.org/browse/DOCS-14861
This issue:
- re-adds the checkbox back in for RHEL 7 s390x on the platform support table
- removes the note about s390x being EOL'd
[Platform Support table](https://docs-mongodbcom-staging.corp.mongodb.com/database-tools/docsworker-xlarge/DOCS-14861-Remove-Platform-Support-EOL-Notice-for-zSeries/installation/installation/#platform-support)

removes EOL notice re RHEL 7 and adds checkmark in to indicate support on s390x

---

source/includes/extracts-compatibility.yaml

Description: Update the version compatibility list to add MDB 6.0 and remove MDB 4.0.
JIRA: https://jira.mongodb.org/browse/DOCSP-24503
Staged: [mongodump - Compatibility](https://docs-mongodbcom-staging.corp.mongodb.com/database-tools/docsworker-xlarge/DOCSP-24503/mongodump/#compatibility) (All other tool pages are also affected by this change. I'm just including one example link.)

DOCSP-24503): Add MDB 6.0 to list of supported versions

---

source/includes/fact-platform-support.rst
source/installation/installation-linux.txt

STAGING
[Installation](https://docs-mongodbcom-staging.corp.mongodb.com/database-tools/docsworker-xlarge/DOCSP-29004-outdated-version-info/installation/installation)
[Installation-linux](https://docs-mongodbcom-staging.corp.mongodb.com/database-tools/docsworker-xlarge/DOCSP-29004-outdated-version-info/installation/installation-linux/#platform-support
)
[JIRA](https://jira.mongodb.org/browse/DOCSP-29004)
[DB Tools] Outdated information on the Database Tools installation page
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=644aa7177efd2382b306dcc2) - unrelated build errors

DCOSP-29004 outdate version info

---

source/mongoexport.txt

Resolves 404'ing hyperlink in [mongoexport](https://www.mongodb.com/docs/atlasMongoDB%20Atlas%20%3C/?tck=docs_server%3E`) page.
https://docs-mongodbcom-staging.corp.mongodb.com/database-tools/docsworker-xlarge/DOCSP-31005-dbtools-404s/mongoexport/#examples:~:text=when%20connecting%20to%20a-,MongoDB%20Atlas,-cluster.
https://jira.mongodb.org/browse/DOCSP-31005
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=649b52d2423952aeb905efae

DOCSP-31005 DBTools 404s

---

source/mongorestore.txt

specify that indexes are built before data is restored by `mongorestore`
https://docs-mongodbcom-staging.corp.mongodb.com/database-tools/docsworker-xlarge/DOCSP-4849-indexes-before-import/mongorestore/#rebuild-indexes
https://jira.mongodb.org/browse/DOCSP-4849
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64aeed5a423952aeb9a6e4d9

DOCSP-4849: indexes are built before data restored

---

source/mongodump.txt

Update [`--oplog` note](https://www.mongodb.com/docs/database-tools/mongodump/#std-option-mongodump.--oplog) to include `--dumpDbUsersAndRoles` as an invalid option.
[mongodump](https://docs-mongodbcom-staging.corp.mongodb.com/database-tools/docsworker-xlarge/docs-9602/mongodump/#std-option-mongodump.--oplog)
[DOCS-9602](https://jira.mongodb.org/browse/DOCS-9602)
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64ae994c423952aeb97cfcfd

DOCS-9602: Update --oplog note

---

source/mongodump.txt

Adding a behavior section to the mongodump page, that calls out providing a MongoDB URI without authSource will use the ``--db`` database for authentication purposes.
https://docs-mongodbcom-staging.corp.mongodb.com/database-tools/docsworker-xlarge/DOCS-16217/mongodump/#using-mongodump-without-an-authsource
https://docs-mongodbcom-staging.corp.mongodb.com/database-tools/docsworker-xlarge/DOCS-16217/mongodump/#authenticating-to-a-specific-database-with-mongodump
https://jira.mongodb.org/browse/DOCS-16217
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64c95b0587b3b36046013b1c

DOCS-16217 Add Authsource Behavior to MongoDump Page

---

source/mongorestore.txt

Small correction to index rebuild blurb when using `mongorestore`.
https://docs-mongodbcom-staging.corp.mongodb.com/database-tools/docsworker-xlarge/DOCSP-31559/mongorestore/#rebuild-indexes
https://jira.mongodb.org/browse/DOCSP-31559
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64ca7ffe87b3b36046467810

DOCSP-31559 Mongorestore Index Blurb Clarification

---

source/includes/fact-match-dump-restore-versions.rst

Updating include file on the mongodump/restore page that clarifys version requirements when dumping and restoring from MongoDB deployment versions.
https://docs-mongodbcom-staging.corp.mongodb.com/database-tools/docsworker-xlarge/DOCSP-17316/mongodump/#restore-to-matching-server-version
https://jira.mongodb.org/browse/DOCSP-17316
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64d25dc767dbe91010e89824

DOCSP-17316 Update mongodump/restore Behavior

---

source/mongostat.txt

Adds minor line on what `mongostat` is used for.
[mongostat](https://docs-mongodbcom-staging.corp.mongodb.com/database-tools/docsworker-xlarge/DOCSP-19590-monogstat-purpose/mongostat/#synopsis)
[DOCSP-19590](https://jira.mongodb.org/browse/DOCSP-19590)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64c1a02f87b3b3604658f9e0)

DOCSP-19590 mongostat usage line

---

source/mongodump.txt
source/mongoexport.txt

Updates suppressed message list for `--quiet` option on `mongodump` and `mongoexport`.
* [mongoexport](https://docs-mongodbcom-staging.corp.mongodb.com/database-tools/docsworker-xlarge/DOCSP-32381-mongodump-quiet/mongoexport/#std-option-mongoexport.--quiet)
* [mongodump](https://docs-mongodbcom-staging.corp.mongodb.com/database-tools/docsworker-xlarge/DOCSP-32381-mongodump-quiet/mongodump/#std-option-mongodump.--quiet)
* [DOCSP-32381](https://jira.mongodb.org/browse/DOCSP-32381)
* [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64e3e93c57e37806c50dcb99)
* [Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=64f258c224fcc731b48cb498)
[What's expected of an external …

DOCSP-32381 Updates --quiet option for mongodump and mongoexport

---

source/includes/warning-read-preference-mongos.rst
source/mongodump.txt
source/mongoexport.txt
source/mongofiles.txt

Removing warning about read preferences
https://preview-mongodbltranmdb2.gatsbyjs.io/database-tools/DOCSP-33804/mongodump/#std-option-mongodump.--readPreference
https://preview-mongodbltranmdb2.gatsbyjs.io/database-tools/DOCSP-33804/mongoexport/#std-option-mongoexport.--readPreference
https://preview-mongodbltranmdb2.gatsbyjs.io/database-tools/DOCSP-33804/mongofiles/#std-option-mongofiles.--readPreference
https://jira.mongodb.org/browse/DOCSP-33804
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6532bc1e3ede3ec111a41e18

DOCSP 33804 - removing read preference warning

---

source/includes/extracts-compatibility.yaml
source/mongoimport.txt

- mongoimport doesn't list support for 7.0
- removed mentions of support for 4.0
[mongoimport](https://preview-mongodbnvillahermosamdb.gatsbyjs.io/database-tools/DOCSP-33929-list-7.0-support-for-mongoimport/mongoimport/)
https://jira.mongodb.org/browse/DOCSP-33929
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6543e730bd8a7a957949e460

Docsp 33929 list 7.0 support for mongoimport

---

source/mongodump.txt

Adds `$regex` syntax example to `mongodump` page
https://preview-mongodbajhuhmdb.gatsbyjs.io/database-tools/DOCSP-33881-mongodump-regex-syntax/mongodump/#std-option-mongodump.--query
https://jira.mongodb.org/browse/DOCSP-33881
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=655528685b686d6bd9b0d365

DOCSP-33881 mongdump $regex example

---

source/includes/changelogs/releases/100.7.1.rst

Add Go compiler version to 100.7.1 changelogs. 
https://preview-mongodbsaraholsonmongodb.gatsbyjs.io/database-tools/DOCS-16185/release-notes/database-tools-changelog/#100.7.1-changelog
https://jira.mongodb.org/browse/DOCS-16185
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65bc45c06b2f17c95aed7ef2

DOCS-16186: Add GO compiler info to changelog for 100.7.1

---

.vscode/settings.json
source/includes/changelogs/releases/100.9.1.rst

Add warning to 100.9.1 changelog regarding field reordering for view pipelines and schema validations. 
https://preview-mongodbjocelynmendez1.gatsbyjs.io/database-tools/DOCSP-35356/release-notes/database-tools-changelog/#100.9.1-changelog
https://jira.mongodb.org/browse/DOCSP-35356
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65c53c416b2f17c95a46df36

DOCSP-35356 field reordering 

---

source/mongodump.txt
source/mongorestore.txt

Adds documentation for mongodump and mongorestore limitations with free and shared Atlas clusters
- https://preview-mongodbkanchanamongodb.gatsbyjs.io/database-tools/DOCS-15886/mongodump/#using-mongodump-on-atlas-cluster
- https://preview-mongodbkanchanamongodb.gatsbyjs.io/database-tools/DOCS-15886/mongorestore/#using-mongorestore-on-atlas-cluster
https://jira.mongodb.org/browse/DOCS-15886
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65c5568e6b2f17c95a52c551

DOCSP-15886 doc limitations with shared clusters

---

source/includes/extracts-clone-copy-db-examples.yaml
source/mongorestore.txt

Looks like mongorestore fails to copy/clone an existing database to a new one on Windows if nsfrom and nsTo values are inside single quotes; only double quotes work on windows. In my testing, double quotes work on mac too. Instead of documenting the right type of quotes to use for each OS, I replaced the quotes in the examples so it will work on mac and windows.
https://preview-mongodbkanchanamongodb.gatsbyjs.io/database-tools/DOCS-15555/mongodump
https://preview-mongodbkanchanamongodb.gatsbyjs.io/database-tools/DOCS-15555/mongorestore
https://jira.mongodb.org/browse/DOCS-15555
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65c655956b2f17c95a916fc2
[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+th …

DOCS-15555 mongorestore fails to copy/clone an existing database to a new one

---

source/mongoimport.txt

Responded to user feedback by clarifying associated indexes are also removed after I verified with dev team on #mongo-tools slack channel. Slight editorial tweak as well.
https://preview-mongodbmmavillemdb.gatsbyjs.io/database-tools/DOCSP-27801-mongoimport-drop-indexes-clarification/mongoimport/#std-option-mongoimport.--drop
https://jira.mongodb.org/browse/DOCSP-2780
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65ea36456fc5f0485068de69

DOCSP-27801-mongoimport-drop-indexes-clarification

---

source/mongodump.txt

Upates current mongodump data exclusion behavior.
https://preview-mongodbkanchanamongodb.gatsbyjs.io/database-tools/DOCSP-30862/mongodump/#data-exclusion
https://jira.mongodb.org/browse/DOCSP-30862
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65e8aa4311db7b0427206d82

DOCSP-30862 Document excluded-by-default databases and collections

---

source/includes/fact-default-no-db-or-uri.rst
source/mongoimport.txt

Adds note about `mongoimport` using the `test` database by default if a db isn't specified w/ the `--db` or `--uri` option.
- [`--db`](https://preview-mongodbajhuhmdb.gatsbyjs.io/database-tools/DOCSP-38145-mongoimport-default-db/mongoimport/#std-option-mongoimport.--db)
- [`--uri`](https://preview-mongodbajhuhmdb.gatsbyjs.io/database-tools/DOCSP-38145-mongoimport-default-db/mongoimport/#std-option-mongoimport.--uri)
https://jira.mongodb.org/browse/DOCSP-38145
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=660acb6c3a5920a291eb24e9

DOCSP-38145 mongoimport default db

---

source/includes/extracts-clone-copy-db-examples.yaml
source/mongodump/mongodump-examples.txt

Removing the pipe command in mongodump / restore example with the `|` operator. 
https://preview-mongodbianfmongodb.gatsbyjs.io/database-tools/DOCSP-38268/mongodump/mongodump-examples/#copy-and-clone-database
https://jira.mongodb.org/browse/DOCSP-38268
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=660dba573a5920a291c79a66

DOCSP-38268 Add Piping Guidance to Examples

---

source/mongodump/mongodump-examples.txt

Removes additional piping example from the mongodump docs.
https://preview-mongodbianfmongodb.gatsbyjs.io/database-tools/DOCSP-38268-b/mongodump/mongodump-examples/#output-an-archive-to-standard-output
https://jira.mongodb.org/browse/DOCSP-38268
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=661d151c3a5920a291481a60

DOCSP-38268 Remove Additional Piping Example

---

source/mongodump.txt
source/mongorestore.txt
source/mongorestore/mongorestore-examples.txt

Added point in time info per Jira.
https://preview-mongodbjasonpricemongodb.gatsbyjs.io/database-tools/DOCSP-33862-mongorestore-example/mongorestore/mongorestore-examples/#back-up-and-restore-a-database-to-a-specific-point-in-time
https://preview-mongodbjasonpricemongodb.gatsbyjs.io/database-tools/DOCSP-33862-mongorestore-example/mongorestore/#options
https://preview-mongodbjasonpricemongodb.gatsbyjs.io/database-tools/DOCSP-33862-mongorestore-example/mongodump/#options
https://jira.mongodb.org/browse/DOCSP-33862
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=661eb3b53a5920a291b8b3a7

DOCSP-33862-mongorestore-example

---

source/mongodump.txt

Added extra details for mongodump per request. 
Unfortunately, we cannot doc both mongodump and mongorestore on the same page because of how the docs platform works. Each set of options tags on a doc page must be tied to the tool tag itself ("mongodump" or "mongorestore"). We also have a docs standards requirement to try to keep pages shorter. Added other details per JIRA.
https://preview-mongodbjasonpricemongodb.gatsbyjs.io/database-tools/DOCSP-39421-detailed-extras/mongodump/#definition
https://jira.mongodb.org/browse/DOCSP-39421
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=664e64b6cf5bec1c29d25d35

DOCSP-39421-detailed-extras

---

source/includes/fact-debian8-eol.rst
source/includes/fact-platform-support.rst
source/installation/installation-linux.txt

- Removes Debian 8 references from database tools support.
- This change will also be referenced in the ``100.9.5`` release notes as part of another PR.
https://preview-mongodbianfmongodb.gatsbyjs.io/database-tools/DOCSP-40296/installation/installation-linux/#platform-support
https://preview-mongodbianfmongodb.gatsbyjs.io/database-tools/DOCSP-40296/installation/installation/#platform-support
https://jira.mongodb.org/browse/DOCSP-40296
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6668700eebce19f314edce18

DOCSP-40296 Remove Debian 8 Support Documentation

---

source/mongostat.txt

Currently, `mongostat` docs use a table that has incorrect formatting.
This PR migrates that table content to a `.. list-table::` directive
The updated table is just above this anchor link, in the `repl` field description.
https://preview-mongodbjwilsonmdb.gatsbyjs.io/database-tools/DOCSP-39633/mongostat/#additional-information
https://jira.mongodb.org/browse/DOCSP-39633
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=667b398cebce19f31413949c

DOCSP-39633 fixes mongostat table format

---

source/mongodump.txt
source/mongoexport.txt

recommend users pause operations on sharded clusters during export
https://preview-mongodbltranmdb2.gatsbyjs.io/database-tools/DOCSP-38679/mongoexport/
https://preview-mongodbltranmdb2.gatsbyjs.io/database-tools/DOCSP-38679/mongodump/
https://jira.mongodb.org/browse/DOCSP-38679
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=669818eb26eba79552d02c08

DOCSP-38679 mongoexport consistency consideration

---

source/bsondump.txt
source/index.txt
source/installation/installation.txt
source/mongodump.txt
source/mongoexport.txt
source/mongoimport.txt
source/mongorestore.txt
source/mongostat.txt
source/mongotop.txt
source/release-notes/database-tools-changelog.txt

Shorten and edit the DB Tools ToC labels with the following guidelines: https://wiki.corp.mongodb.com/pages/viewpage.action?spaceKey=DE&title=FAQ%3A+Table+of+Contents+Labels
Official style guidelines for the ToC: Official Style Guidelines for the ToC: https://www.mongodb.com/docs/meta/style-guide/style/toc-labels/
https://deploy-preview-172--docs-commandline-tools.netlify.app
https://jira.mongodb.org/browse/DOCSP-43304
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66d9fda9f062608452c8e820

DOCSP-43304-DBTools-ToC-update

---

source/includes/fact-platform-support.rst

Adds Debian 11 and 12 to the platform support matrix.
[Platform Support include](https://deploy-preview-171--docs-commandline-tools.netlify.app/mongodump/mongodump-compatibility-and-installation/#platform-support)
[DOCSP-42141](https://jira.mongodb.org/browse/DOCSP-43141)

DOCSP-42141 Adds Debian 11/12 to title matrix

---

source/mongoimport.txt

Quick win; removes a duplicate "RFC" from the `mongoimport` page. 
https://deploy-preview-173--docs-commandline-tools.netlify.app/mongoimport/
https://jira.mongodb.org/browse/DOCSP-43376
See below.

DOCSP-43376 removing duplicate word

---

source/includes/extracts-compatibility.yaml

Updates version support to include v8.0
The updated file is used to show 8.0 compatibility for:
- [General Installation](https://deploy-preview-174--docs-commandline-tools.netlify.app/installation/installation/#mongodb-server-compatibility) and the Windows/Mac/Linux sub-pages
- [`mongodump` compatibility](https://deploy-preview-174--docs-commandline-tools.netlify.app/mongodump/mongodump-compatibility-and-installation/#mongodb-server-compatibility)
- [`mongorestore` compatibility](https://deploy-preview-174--docs-commandline-tools.netlify.app/mongorestore/mongorestore-compatibility-and-installation/#mongodb-server-compatibility)
- [`bsondump` compatibility](https://deploy-preview-174--docs-commandline-tools.netlify.app/bsondump/bsondump-compatibility-and-installation/#mongodb-server-compati …

DOCSP-41816 updates tools version support to include 8.0

---

source/includes/fact-target-cluster-rollbacks.rst
source/mongodump/mongodump-behavior.txt
source/mongorestore/mongorestore-behavior-access-usage.txt

add a note about rollbacks in [`mongodump`](https://www.mongodb.com/docs/database-tools/mongodump/mongodump-behavior/) & [`mongorestore`](https://www.mongodb.com/docs/database-tools/mongorestore/mongorestore-behavior-access-usage/)'s behavior sections about rollback on the target cluster during a restore or import to account for the effects of [TOOLS-3696](https://jira.mongodb.org/browse/TOOLS-3696).
- https://deploy-preview-176--docs-commandline-tools.netlify.app/mongodump/mongodump-behavior/#using-mongodump-on-atlas-free-and-shared-tier-clusters
- https://deploy-preview-176--docs-commandline-tools.netlify.app/mongorestore/mongorestore-behavior-access-usage/#using-mongorestore-on-atlas-free-and-shared-tier-clusters
https://jira.mongodb.org/browse/DOCSP-44864
[What's expected of an …

DOCSP-44864-redo-restore-import-if-rollback

---

source/mongodump.txt
source/mongorestore.txt
source/mongorestore/mongorestore-examples.txt

Note that QE isn't supported with `mongodump` and `mongorestore`
- Also remove QE `mongorestore` example
See discussion in this [Slack thread](https://mongodb.slack.com/archives/C039YP9P7G9/p1732303595603359).
- [mongorestore](https://deploy-preview-177--docs-commandline-tools.netlify.app/mongorestore/#mongorestore)
- [mongodump](https://deploy-preview-177--docs-commandline-tools.netlify.app/mongodump/#:~:text=binary%20archive%20file.-,IMPORTANT,-You%20can%27t%20use)
[DOCSP-45578](https://jira.mongodb.org/browse/DOCSP-45578)

DOCSP-45578-no-QE-support

---

source/includes/fact-nsExclude-precedence.rst
source/mongorestore.txt

Documents that ``--nsExclude`` takes precedence over ``--nsInclude`` in cases where both are specified.
**Test Results**: https://gist.github.com/jmd-mongo/63690ba41fcea86fcb8880902559b992
- https://deploy-preview-178--docs-commandline-tools.netlify.app/mongorestore/#std-option-mongorestore.--nsExclude
- https://deploy-preview-178--docs-commandline-tools.netlify.app/mongorestore/#std-option-mongorestore.--nsInclude
https://jira.mongodb.org/browse/DOCSP-24948

DOCSP-24948-mongorestore-nsExclude-nsInclude-precedence

---

source/includes/fact-compressors-option-desc.rst
source/mongodump.txt
source/mongorestore.txt

Document the compressors option for mongodump and mongorestore
- [mongodump Options](https://deploy-preview-179--docs-commandline-tools.netlify.app/mongodump/#std-option-mongodump.--compressors)
- [mongorestore Options](https://deploy-preview-179--docs-commandline-tools.netlify.app/mongorestore/#std-option-mongorestore.--compressors)
https://jira.mongodb.org/browse/DOCSP-45728

DOCSP-45728-compressors-option

---

source/mongorestore.txt

- ``restoreDbUsersAndRoles`` requires ``dumpDbUsersAndRoles``
- This PR also cleans up wording about using``restoreDbUsersAndRoles`` on the ``admin`` database.
https://deploy-preview-182--docs-commandline-tools.netlify.app/mongorestore/#std-option-mongorestore.--restoreDbUsersAndRoles
https://jira.mongodb.org/browse/DOCSP-46246

add note that restoreDbUsersAndRoles requires dumpDbUsersAndRoles

---

source/mongodump.txt

Explicitly notes limitation that you can't run `mongodump` with `--oplog` on sharded clusters.
https://deploy-preview-189--docs-commandline-tools.netlify.app/mongodump/#std-option-mongodump.--oplog:~:text=You%20can%27t%20run%20mongodump%20with%20%2D%2Doplog%20on%20a%20sharded%20cluster.%20To%20back%20up%20sharded%20clusters%20with%20mongodump%2C%20see%20Back%20Up%20a%20Self%2DManaged%20Sharded%20Cluster%20with%20a%20Database%20Dump.
https://jira.mongodb.org/browse/DOCSP-48055

DOCSP-48055-mongodump-oplog-sharding-limit

---

source/mongostat/mongostat-behavior.txt

Adds a note that `directShardOperations` role is required to use `mongostat` on an 8.0 sharded cluster.
[Note](https://deploy-preview-190--docs-commandline-tools.netlify.app/mongostat/mongostat-behavior/#required-access)
[DOCSP-24323](https://jira.mongodb.org/browse/DOCSP-24323)

DOCSP-24323: directShardOperations req for mongostat

---

snooty.toml

Changes the `title` field in Snooty. This doesn't appear to be used in staging, so presumably it gets pulled in from somewhere else.
[DOCSP-48291](https://jira.mongodb.org/browse/DOCSP-48291)

DOCSP-48291 Snooty Title

---

source/mongodump.txt

Updates documentation for `excludeCollection` and `excludeCollectionsWithPrefix` options to state that a database must be specified.
- https://deploy-preview-195--docs-commandline-tools.netlify.app/mongodump/#std-option-mongodump.--excludeCollection
- https://deploy-preview-195--docs-commandline-tools.netlify.app/mongodump/#std-option-mongodump.--excludeCollectionsWithPrefix
https://jira.mongodb.org/browse/DOCSP-49213

DOCSP-49213 documents db name requirement for excludeCollection options

---

source/mongoimport/mongoimport-behavior.txt

Add timeseries limitations to mongoimport behavior
https://deploy-preview-197--docs-commandline-tools.netlify.app/mongoimport/mongoimport-behavior/
https://jira.mongodb.org/browse/DOCSP-47144
https://app.netlify.com/sites/docs-commandline-tools/deploys/6807fed2f4712b0008334059

DOCSP-47144-timeseries-limitations

---

source/mongorestore/mongorestore-behavior-access-usage.txt

We're not consistent in our use of fCV versus FCV. Let's standardize our docs set so that all instances are FCV. 
https://deploy-preview-180--docs-commandline-tools.netlify.app/mongorestore/mongorestore-behavior-access-usage/
[DOCSP-43739](https://jira.mongodb.org/browse/DOCSP-43739)
See the [taxonomy tagging instructions](https://wiki.corp.mongodb.com/display/DE/Taxonomy+tagging+instructions) and this [example PR](https://github.com/10gen/cloud-docs/pull/5042/files) 

(DOCSP-43739) Standardize FCV
