source/includes/extracts-download-from-tools.yaml, source/includes/extracts-sharded-clusters-backup-restore-limitations.yaml, source/includes/list-table-auth-mechanisms.rst, source/index.txt
https://jira.mongodb.org/browse/DOCSP-9267
=> DOCSP-9267 - Change jmp parameter to tck.

source/mongodump.txt, source/mongoexport.txt, source/mongofiles.txt, source/mongoimport.txt, source/mongorestore.txt, source/mongostat.txt, source/mongotop.txt
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=621566439c4c7f6bfba2ff34
https://jira.mongodb.org/browse/DOCSP-20988
TOOLS] Fix build errors
=> DOCSP-20988 Fix build errors

source/mongostat.txt
https://docs-mongodbcom-staging.corp.mongodb.com/database-tools/docsworker-xlarge/DOCSP-20688-additional-mongostat-examples/mongostat/#std-option-mongostat.-o
https://docs-mongodbcom-staging.corp.mongodb.com/database-tools/docsworker-xlarge/DOCSP-20688-additional-mongostat-examples/mongostat/#add-fields-to--output
https://jira.mongodb.org/browse/DOCSP-20688
[TOOLS] include additional examples for mongostat
=> DOCSP-20688 additional mongostat examples

source/mongodump.txt
https://jira.mongodb.org/browse/DOCSP-24967
https://docs-mongodbcom-staging.corp.mongodb.com/database-tools/docsworker-xlarge/DOCSP-24967-viewsAsCollections-update/mongodump/#mongodump
=> DOCSP-24967 viewsAsCollections-update

source/includes/changelogs/releases/100.6.1.rst, source/release-notes/database-tools-changelog.txt
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/database-tools/docsworker-xlarge/DOCS-15720-100.6.1-release/release-notes/database-tools-changelog/#100.6.1-changelog)
[Jira](https://jira.mongodb.org/browse/DOCS-15720)
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6364306f7f102f5cea7f30da)
=> DOCS-15720 100.6.1 release

source/includes/changelogs/releases/100.5.2.rst, source/includes/changelogs/releases/100.7.0.rst, source/includes/ubuntu-connection.rst, source/mongodump.txt, source/mongorestore.txt
STAGING
[mongodump](https://docs-mongodbcom-staging.corp.mongodb.com/database-tools/docsworker-xlarge/DOCS-15980-ubuntu-compatibility/mongodump/#additional-considerations)
[mongorestore](https://docs-mongodbcom-staging.corp.mongodb.com/database-tools/docsworker-xlarge/DOCS-15980-ubuntu-compatibility/mongorestore/#additional-considerations)
[JIRA](https://jira.mongodb.org/browse/DOCS-15980)
[Tools] mongodump/mongorestore compatibility issue w/ Ubuntu 18.0.4
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=642dbe92b49106a498a74089)
=> DOCS-15980 ubuntu compatibility

source/includes/changelogs/releases/100.7.2.rst, source/release-notes/database-tools-changelog.txt
Adds 100.7.2 changelog.
https://docs-mongodbcom-staging.corp.mongodb.com/database-tools/docsworker-xlarge/DOCS-16171-tools-release-100.7.2/release-notes/database-tools-changelog/
https://jira.mongodb.org/browse/DOCS-16171
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=647e556d67a273b816940acb
=> DOCS-16171: Adds 100.7.2 changelog

source/facets.toml, source/release-notes/facets.toml
https://jira.mongodb.org/browse/DOCSP-32483
Hey @sarah-olson-mongodb!  Here's another set of facet.toml files for you, for the command line tools repo.  Please merge if everything looks good to you!
Thanks!
Sarah
=> DOCSP-32483 programmatic tagging script for command line tools repo

source/includes/fact-migrate-atlas.rst, source/index.txt, source/installation/installation-linux.txt, source/installation/installation-windows.txt, source/installation/installation.txt, source/mongoexport.txt, source/mongoimport.txt, source/mongorestore.txt
Adds an Atlas-centric CTA to the top 250 pages in the database-tools docs repo
https://preview-mongodbsarahsimpers.gatsbyjs.io/database-tools/DOCSP-32259/
https://preview-mongodbsarahsimpers.gatsbyjs.io/database-tools/DOCSP-32259/mongoimport/
https://preview-mongodbsarahsimpers.gatsbyjs.io/database-tools/DOCSP-32259/mongoexport/
https://preview-mongodbsarahsimpers.gatsbyjs.io/database-tools/DOCSP-32259/mongorestore/
https://preview-mongodbsarahsimpers.gatsbyjs.io/database-tools/DOCSP-32259/installation/installation-linux/
https://preview-mongodbsarahsimpers.gatsbyjs.io/database-tools/DOCSP-32259/installation/installation/
https://preview-mongodbsarahsimpers.gatsbyjs.io/database-tools/DOCSP-32259/installation/installation-windows/
https://jira.mongodb.org/browse/DOCSP-32259 …
=> (DOCSP-32259)(DOCSP-32262)(DOCSP-32264)(DOCSP-32265)(DOCSP-32266)(DOCSP-32293)(DOCSP-32263) Makes tools pages Atlas-centric

source/mongodump.txt
Adds a CTA to the mongodump page
https://preview-mongodbsarahsimpers.gatsbyjs.io/database-tools/DOCSP-32024/mongodump/
https://jira.mongodb.org/browse/DOCSP-32024
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65086581492df295cf71e9fe
=> (DOCSP-32024) Adds CTA to mongodump page

source/installation/installation-linux.txt, source/installation/installation-windows.txt, source/installation/installation.txt, source/mongodump.txt, source/mongoexport.txt, source/mongoimport.txt, source/mongorestore.txt
@sarah-olson-mongodb - here are the manual tags for the commandline tools repo.  This is my first pass through this repo, so hopefully they're right the first time! ;)
Thank you!
Sarah
=> DOCSP-27817 manual tagging on database-tools top 250 pages

source/mongorestore.txt
Reverts mongodb/docs-commandline-tools#109
=> Revert "DOCSP-31011 Add Mongorestore Time Series Collection"

source/includes/changelogs/releases/100.9.0.rst, source/release-notes/database-tools-changelog.txt
- Adds 100.9.0 changelog to release notes 
https://preview-mongodbajhuhmdb.gatsbyjs.io/database-tools/DOCSP-33546-100.9.0-RN/release-notes/database-tools-changelog/#100.9.0-changelog
https://jira.mongodb.org/browse/DOCSP-33546
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=654a59ad5b686d6bd9095ba1
=> DOCSP-33546 DBTools 100.9.0 RN

source/includes/changelogs/releases/100.9.1.rst, source/release-notes/database-tools-changelog.txt
100.9.1 database tools release notes
https://preview-mongodbltranmdb2.gatsbyjs.io/database-tools/DOCSP-33835/release-notes/database-tools-changelog/
https://jira.mongodb.org/browse/DOCSP-33835
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=654e8d465b686d6bd92f9d24
=> DOCSP-33835 100.9.1 release notes

source/includes/changelogs/releases/100.9.4.rst, source/release-notes/database-tools-changelog.txt
Release Notes for Database Tools 100.9.4.
https://preview-mongodbjmdmongo.gatsbyjs.io/database-tools/DOCSP-34657/release-notes/database-tools-changelog/#100.9.4-changelog
https://jira.mongodb.org/browse/DOCSP-34657
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=657234087a5cb5fef5ef7d12
=> DOCSP-34657 release notes for 100.9.4

source/mongodump.txt
Clarify the purposes of mongodump's metadata and archive outputs
https://preview-mongodbltranmdb2.gatsbyjs.io/database-tools/DOCSP-35719/mongodump/#metadata-output
https://jira.mongodb.org/browse/DOCSP-35719
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65b909936b2f17c95ad0f9a7
=> DOCSP 35719 Clarify purposes of mongodump's metadata

source/mongoexport.txt
Documents  --queryFile option for mongoexport. Tested with the records collection (shown in the page) and works as documented.
https://preview-mongodbkanchanamongodb.gatsbyjs.io/database-tools/DOCSP-16037/mongoexport/#std-option-mongoexport.--queryFile
https://jira.mongodb.org/browse/DOCS-16037
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65c67f956b2f17c95aa2409f
=> DOCS-16037 documentation for --queryFile option

source/mongorestore.txt
Documents fixDottedHashIndex option
https://preview-mongodbkanchanamongodb.gatsbyjs.io/database-tools/DOCSP-15210/mongorestore/#std-option-mongorestore.--fixDottedHashIndex
https://jira.mongodb.org/browse/DOCSP-15210
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65e6013811db7b042759ca44
=> DOCSP-15210 document fixDottedHashIndex option

source/mongodump/mongodump-behavior.txt, source/mongorestore.txt
Fixing build errors
N/A
https://jira.mongodb.org/browse/DOCSP-38105
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6604833d6fc5f048508fb0cc
=> DOCSP-38105 fixing build errors

source/includes/fact-mongodump-mongorestore-use-cases.rst, source/mongoexport.txt, source/mongoimport.txt
recommending mongodump and mongorestore for backing up and restoring or roundtripping data
https://preview-mongodbltranmdb2.gatsbyjs.io/database-tools/DOCSP-37692/mongoimport/#mongodb-binary-bin.mongoimport
https://preview-mongodbltranmdb2.gatsbyjs.io/database-tools/DOCSP-37692/mongoexport/
https://jira.mongodb.org/browse/DOCSP-37692
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65f202ae6fc5f0485034e168
=> DOCSP 37692 recommendation for mongodump and mongorestore

snooty.toml, source/includes/extracts-run-from-cmd.yaml, source/mongoexport.txt, source/mongoexport/mongoexport-behavior.txt, source/mongoexport/mongoexport-compatibility-and-installation.txt, source/mongoexport/mongoexport-examples.txt
- Reduces the size of the mongoexport reference topic by splitting off the install info, behavior, and examples into respective subtopics
- Removes self-links
- Removes redundant extract
[mongoexport](https://preview-mongodbnvillahermosamdb.gatsbyjs.io/database-tools/DOCSP-37841-split-mongoexport-page/mongoexport/)
[mongoexport Compatibility and Installation](https://preview-mongodbnvillahermosamdb.gatsbyjs.io/database-tools/DOCSP-37841-split-mongoexport-page/mongoexport/mongoexport-compatibility-and-installation/)
[mongoexport Behavior, Access, and Usage](https://preview-mongodbnvillahermosamdb.gatsbyjs.io/database-tools/DOCSP-37841-split-mongoexport-page/mongoexport/mongoexport-behavior/)
[mongoexport Examples](https://preview-mongodbnvillahermosamdb.gatsbyjs.io/database-tools/DOCSP-3784 …
=> DOCSP-37841 Split mongoexport page

snooty.toml, source/includes/extracts-run-from-cmd.yaml, source/mongostat.txt, source/mongostat/mongostat-behavior.txt, source/mongostat/mongostat-compatibility-and-installation.txt, source/mongostat/mongostat-examples.txt
- Reduces the size of the mongostat reference topic by splitting off the install info, behavior, and examples into respective subtopics
- Removes self-links
- Removes redundant extract
[mongostat](https://preview-mongodbnvillahermosamdb.gatsbyjs.io/database-tools/DOCSP-37842-split-mongostat-page/mongostat/)
[mongostat Compatibility and Installation](https://preview-mongodbnvillahermosamdb.gatsbyjs.io/database-tools/DOCSP-37842-split-mongostat-page/mongostat/mongostat-compatibility-and-installation/)
[mongostat Behavior, Access, and Usage](https://preview-mongodbnvillahermosamdb.gatsbyjs.io/database-tools/DOCSP-37842-split-mongostat-page/mongostat/mongostat-behavior/)
[mongostat Examples](https://preview-mongodbnvillahermosamdb.gatsbyjs.io/database-tools/DOCSP-37842-split-mongostat-page/mon …
=> DOCSP-37842 split mongostat page

snooty.toml, source/includes/extracts-run-from-cmd.yaml, source/mongotop.txt, source/mongotop/mongotop-behavior.txt, source/mongotop/mongotop-compatibility-and-installation.txt, source/mongotop/mongotop-examples.txt
- Reduces the size of the mongotop reference topic by splitting off the install info, behavior, and examples into respective subtopics
- Removes self-links
- Removes redundant extract
[mongotop ](https://preview-mongodbnvillahermosamdb.gatsbyjs.io/database-tools/DOCSP-37843-split-mongotop-page/mongotop/)
[mongotop Compatibility and Installation](https://preview-mongodbnvillahermosamdb.gatsbyjs.io/database-tools/DOCSP-37843-split-mongotop-page/mongotop/mongotop-compatibility-and-installation/)
[mongotop Behavior, Access, and Usage](https://preview-mongodbnvillahermosamdb.gatsbyjs.io/database-tools/DOCSP-37843-split-mongotop-page/mongotop/mongotop-behavior/)
[mongotop Examples](https://preview-mongodbnvillahermosamdb.gatsbyjs.io/database-tools/DOCSP-37843-split-mongotop-page/mongotop/mongoto …
=> DOCSP-37843 split mongotop page

source/index.txt, source/installation/installation-linux.txt, source/installation/installation-windows.txt, source/installation/installation.txt, source/mongodump.txt, source/mongoexport.txt, source/mongoimport.txt, source/mongorestore.txt
Adding meta descriptions for database tools batch 16
n/a
https://jira.mongodb.org/browse/DOCSP-38256
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=661843ff3a5920a2915730a9
=> DOCSP-38256 meta description batch 16

source/mongoimport.txt
Add a callout to the mongo dump import and export page that you can also import and export with Compass.
https://preview-mongodbianfmongodb.gatsbyjs.io/database-tools/DOCSP-38331/mongoimport/
https://jira.mongodb.org/browse/DOCSP-38331
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=661d8fbf3a5920a29170ecf1
=> DOCSP-38331 Add Alternative Compass Import Export Note

snooty.toml, source/includes/changelogs/dbtools-changelogs.rst, source/includes/changelogs/releases/100.1.0.rst, source/release-notes/database-tools-changelog.txt, source/release-notes/dbtools-1.0-changelog.txt, source/release-notes/dbtools-1.1-changelog.txt, source/release-notes/dbtools-1.2-changelog.txt, source/release-notes/dbtools-1.3-changelog.txt, source/release-notes/dbtools-1.4-changelog.txt, source/release-notes/dbtools-1.5-changelog.txt, source/release-notes/dbtools-1.6-changelog.txt, source/release-notes/dbtools-1.7-changelog.txt, source/release-notes/dbtools-1.8-changelog.txt
Breaks the database tools changelog page down by minor versions to improve page performance
[Database Tools 1.9 Changelog](https://preview-mongodbnvillahermosamdb.gatsbyjs.io/database-tools/DOCSP-37845-dbtools-changelog-refactor/release-notes/database-tools-changelog/)
https://jira.mongodb.org/browse/DOCSP-37845
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=661ed96c3a5920a291c583a0
=> DOCSP-37845 Refactor DBTools changelog

source/mongorestore/mongorestore-examples.txt
Removing additional MongoRestore Pipe example, which is a bad practice.
https://preview-mongodbianfmongodb.gatsbyjs.io/database-tools/DOCSP-38268-c/mongorestore/mongorestore-examples/#restore-from-compressed-data
https://jira.mongodb.org/browse/DOCSP-38268
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66202a023a5920a29121dba7
=> DOCSP-38268 Remove MongoRestore Pipe Example

source/includes/mongodump-mongorestore-consistent-data.rst, source/includes/mongodump-mongorestore-learn-more.rst, source/mongodump/mongodump-examples.txt, source/mongorestore/mongorestore-examples.txt
Additional example details and links.
https://preview-mongodbjasonpricemongodb.gatsbyjs.io/database-tools/DOCSP-39420-additional-example-details/mongorestore/mongorestore-examples/#create-and-restore-consistent-backup-files
https://preview-mongodbjasonpricemongodb.gatsbyjs.io/database-tools/DOCSP-39420-additional-example-details/mongodump/mongodump-examples/#create-and-restore-consistent-backup-files
https://jira.mongodb.org/browse/DOCSP-39420
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=665fa66ccf5bec1c296eba09
=> DOCSP-39420-additional-example-details

source/mongoimport.txt
fixing mongoimport Go date example input
https://preview-mongodbltranmdb2.gatsbyjs.io/database-tools/DOCSP-24685/mongoimport/#std-option-mongoimport.--columnsHaveTypes
https://jira.mongodb.org/browse/DOCSP-24658
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=668d4286fb8bd13b84696e53
=> DOCSP-24685 fixing mongoimport date argument

source/index.txt
Recommend users use the latest release version for database tools
https://preview-mongodbjocelynmendez1.gatsbyjs.io/database-tools/DOCSP-40745/
https://jira.mongodb.org/browse/DOCSP-40745?filter=-1
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66a3c6ea26eba795526c1284
=> DOCSP-40745  Version support disclaimer at the top-level database tools page

source/mongoexport.txt
Add backup tutorial links
https://preview-mongodbltranmdb2.gatsbyjs.io/database-tools/DOCSP-41895/mongoexport/
https://jira.mongodb.org/browse/DOCSP-41895
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=66abaec9824f175afdbf5cbd
=> DOCSP-41895 adding backup tutorial

source/includes/mongodump-restore-version-link.rst
Updates `mongodump` and `mongorestore` landing pages to clarify their behavior wrt version and FCV
[`mongodump`](https://deploy-preview-175--docs-commandline-tools.netlify.app/mongodump/)
[`mongorestore`](https://deploy-preview-175--docs-commandline-tools.netlify.app/mongorestore/)
https://jira.mongodb.org/browse/DOCSP-45089
=> DOCSP-45089 clarifies mongodump/restore landing pages

source/includes/fact-compressors-option-desc.rst
Clarifies the mongodump compressors option
https://deploy-preview-181--docs-commandline-tools.netlify.app/mongodump/#std-option-mongodump.--compressors
https://jira.mongodb.org/browse/DOCSP-46285
=> DOCSP-46285-mongodump-compressors-clarification

config/redirects
Updates the redirect file to point installation/installation -> /installation
```
mut-redirects config/redirects
Redirect 301 /docs/database-tools/installation/installation https://www.mongodb.com/docs/database-tools/installation
```
https://jira.mongodb.org/browse/DOCSP-46955
=> DOCSP-46955 update redirects file for installation page

config/errors.yaml, source/meta/401.txt, source/meta/403.txt, source/meta/404.txt, source/meta/410.txt
Deletes unused `meta` files as part of TOOLS audit. 
https://jira.mongodb.org/browse/DOCSP-47583
=> DOCSP-47583-audit-untouched-files-meta

source/includes/list-table-auth-mechanisms.rst, source/includes/steps-install-linux-deb.yaml, source/includes/steps-install-linux-tgz.yaml, source/includes/steps-install-macos-zip.yaml, source/includes/steps-install-windows-msi.yaml, source/includes/steps-install-windows-zip.yaml
Audits are tracked here:
https://docs.google.com/spreadsheets/d/1_dhYLKxiS8opuPPQU048ML8bVPbB5RWGIt9lPf6_E1k/edit?gid=2146656553#gid=2146656553
https://jira.mongodb.org/browse/DOCSP-47582
=> DOCSP-47582-untouched-tools-includes

source/mongodump.txt
Updated bullet point and got rid of link
https://deploy-preview-198--docs-commandline-tools.netlify.app/mongodump/#mongodump
https://jira.mongodb.org/browse/DOCSP-49698
=> DOCSP-49698-update-serverless-link
